#!/usr/bin/env bash
set -euo pipefail

# CI check: verify sync-server contracts are thin stubs pointing to shared contracts.

SOURCE_DIR="src/shared/contracts"
TARGET_DIR="sync-server/src/contracts"
MANIFEST_FILE="scripts/contracts-manifest.txt"
SOURCE_IMPORT_PREFIX="../../../src/shared/contracts"
DRIFT=0

if [ ! -f "$MANIFEST_FILE" ]; then
  echo "ERROR: Contract manifest $MANIFEST_FILE not found"
  exit 1
fi

SHARED_FILES=()
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*$ ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
    continue
  fi
  SHARED_FILES+=("$line")
done < "$MANIFEST_FILE"

if [ "${#SHARED_FILES[@]}" -eq 0 ]; then
  echo "ERROR: Contract manifest $MANIFEST_FILE is empty"
  exit 1
fi

for filename in "${SHARED_FILES[@]}"; do
  file="$SOURCE_DIR/$filename"
  target="$TARGET_DIR/$filename"
  source_module="${filename%.ts}"
  expected_content=$(
    cat <<EOF
// Auto-generated by scripts/sync-contracts.sh. Do not edit manually.
export * from '$SOURCE_IMPORT_PREFIX/$source_module'
EOF
  )

  if [ ! -f "$file" ]; then
    echo "MISSING: $filename listed in manifest but missing in $SOURCE_DIR"
    DRIFT=1
    continue
  fi

  if [ ! -f "$target" ]; then
    echo "MISSING: $filename not found in $TARGET_DIR"
    DRIFT=1
    continue
  fi

  if ! diff -q <(printf '%s\n' "$expected_content") "$target" > /dev/null 2>&1; then
    echo "DRIFT: $filename is not a shared-contract re-export stub"
    diff --color=auto <(printf '%s\n' "$expected_content") "$target" || true
    DRIFT=1
  fi
done

# Guardrail: no extra non-test contract files in sync-server.
for path in "$TARGET_DIR"/*.ts; do
  [ -e "$path" ] || continue
  base="$(basename "$path")"
  case "$base" in
    *.test.ts)
      continue
      ;;
  esac

  known=0
  for filename in "${SHARED_FILES[@]}"; do
    if [ "$base" = "$filename" ]; then
      known=1
      break
    fi
  done

  if [ "$known" -eq 0 ]; then
    echo "UNMANAGED: $base exists in $TARGET_DIR but is not listed in $MANIFEST_FILE"
    DRIFT=1
  fi
done

if [ "$DRIFT" -eq 1 ]; then
  echo ""
  echo "Contract drift detected! Run 'pnpm sync:contracts' to fix."
  exit 1
else
  echo "All contracts in sync and sourced from src/shared/contracts"
fi
