#!/usr/bin/env bash
set -euo pipefail

# Generate sync-server contract re-export stubs from shared contracts.
# This keeps src/shared/contracts as the single source of truth.

SOURCE_DIR="src/shared/contracts"
TARGET_DIR="sync-server/src/contracts"
MANIFEST_FILE="scripts/contracts-manifest.txt"
SOURCE_IMPORT_PREFIX="../../../src/shared/contracts"

if [ ! -f "$MANIFEST_FILE" ]; then
  echo "ERROR: Contract manifest $MANIFEST_FILE not found"
  exit 1
fi

SHARED_FILES=()
while IFS= read -r line; do
  if [[ "$line" =~ ^[[:space:]]*$ ]] || [[ "$line" =~ ^[[:space:]]*# ]]; then
    continue
  fi
  SHARED_FILES+=("$line")
done < "$MANIFEST_FILE"

if [ "${#SHARED_FILES[@]}" -eq 0 ]; then
  echo "ERROR: Contract manifest $MANIFEST_FILE is empty"
  exit 1
fi

if [ ! -d "$SOURCE_DIR" ]; then
  echo "ERROR: Source directory $SOURCE_DIR not found"
  exit 1
fi

if [ ! -d "$TARGET_DIR" ]; then
  mkdir -p "$TARGET_DIR"
fi

SYNCED=0
CHANGED=0

for filename in "${SHARED_FILES[@]}"; do
  file="$SOURCE_DIR/$filename"
  target="$TARGET_DIR/$filename"
  source_module="${filename%.ts}"
  expected_content=$(
    cat <<EOF
// Auto-generated by scripts/sync-contracts.sh. Do not edit manually.
export * from '$SOURCE_IMPORT_PREFIX/$source_module'
EOF
  )

  if [ ! -f "$file" ]; then
    echo "ERROR: $filename listed in manifest but missing in $SOURCE_DIR"
    exit 1
  fi

  current_content=""
  if [ -f "$target" ]; then
    current_content="$(cat "$target")"
  fi

  if [ "$current_content" != "$expected_content" ]; then
    printf '%s\n' "$expected_content" > "$target"
    CHANGED=$((CHANGED + 1))
    echo "  Stubbed: $filename"
  fi
  SYNCED=$((SYNCED + 1))
done

if [ "$CHANGED" -eq 0 ]; then
  echo "Contracts already stubbed and in sync ($SYNCED files checked)"
else
  echo "Stubbed $CHANGED/$SYNCED contract files"
fi
